indent = 4
keep_full_version = true
table_format = "long"
sub_table_spacing = "\n"
# Keeping it closer to
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#authors-maintainers
collapse_tables = [
    "project.authors",
    "project.maintainers",
]
# TODO: Remove when https://github.com/tox-dev/toml-fmt/issues/460 is resolved.
max_supported_python = "3.15"
